<?php

use CRM_ApiLog_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_ApiLogConfigs',
    'entity' => 'SavedSearch',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'ApiLogConfigs',
        'label' => E::ts('ApiLogConfigs'),
        'api_entity' => 'ApiLogConfig',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'title',
            'entity_filter',
            'action_filter',
            'request_filter',
            'response_filter',
            'success_filter:label',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => [],
          'join' => [],
          'having' => [],
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_ApiLogConfigs_SearchDisplay_ApiLogConfigs_Table_1',
    'entity' => 'SearchDisplay',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'ApiLogConfigs_Table_1',
        'label' => E::ts('ApiLogConfigs'),
        'saved_search_id.name' => 'ApiLogConfigs',
        'type' => 'table',
        'settings' => [
          'description' => NULL,
          'sort' => [],
          'limit' => 50,
          'pager' => [],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'id',
              'dataType' => 'Integer',
              'label' => E::ts('ID'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'title',
              'dataType' => 'String',
              'label' => E::ts('Title'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'entity_filter',
              'dataType' => 'String',
              'label' => E::ts('Entity Filter'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'action_filter',
              'dataType' => 'Text',
              'label' => E::ts('Action Filter'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'request_filter',
              'dataType' => 'Text',
              'label' => E::ts('Request Filter'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'response_filter',
              'dataType' => 'Text',
              'label' => E::ts('Response Filter'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'success_filter:label',
              'dataType' => 'Integer',
              'label' => E::ts('Success Filter'),
              'sortable' => TRUE,
            ],
            [
              'size' => 'btn-xs',
              'links' => [
                [
                  'path' => 'civicrm/api-log/config/add?reset=1&action=update&id=[id]',
                  'icon' => '',
                  'text' => E::ts('Update'),
                  'style' => 'default',
                  'condition' => [],
                  'task' => '',
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '',
                ],
                [
                  'path' => 'civicrm/api-log/config/delete?reset=1&&action=delete&delete=1&id=[id]',
                  'icon' => '',
                  'text' => E::ts('Delete'),
                  'style' => 'danger',
                  'condition' => [],
                  'task' => '',
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '',
                ],
              ],
              'type' => 'buttons',
              'alignment' => 'text-right',
            ],
          ],
          'actions' => FALSE,
          'classes' => [
            'table',
            'table-striped',
          ],
          'button' => NULL,
          'toolbar' => [
            [
              'path' => 'civicrm/api-log/config/add?reset=1&action=add',
              'icon' => 'fa-plus',
              'text' => E::ts('Add'),
              'style' => 'default',
              'condition' => [],
              'task' => '',
              'entity' => '',
              'action' => '',
              'join' => '',
              'target' => '',
            ],
          ],
          'headerCount' => FALSE,
        ],
      ],
      'match' => [
        'name',
        'saved_search_id',
      ],
    ],
  ],
];