<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from api_log/xml/schema/CRM/ApiLog/ApiLogConfig.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:aa9b83b677bc544d1bc01ede1178d204)
 */
use CRM_ApiLog_ExtensionUtil as E;

/**
 * Database access object for the ApiLogConfig entity.
 */
class CRM_ApiLog_DAO_ApiLogConfig extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_api_log_config';

  /**
   * Field to show when displaying a record.
   *
   * @var string
   */
  public static $_labelField = 'title';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique ApiLogConfig ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $title;

  /**
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $entity_filter;

  /**
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $action_filter;

  /**
   * @var string
   *   (SQL type: longtext)
   *   Note that values will be retrieved from the database as a string.
   */
  public $request_filter;

  /**
   * @var string
   *   (SQL type: longtext)
   *   Note that values will be retrieved from the database as a string.
   */
  public $response_filter;

  /**
   * Success filter based on option group
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $success_filter;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_api_log_config';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Api Log Configs') : E::ts('Api Log Config');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique ApiLogConfig ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_api_log_config.id',
          'table_name' => 'civicrm_api_log_config',
          'entity' => 'ApiLogConfig',
          'bao' => 'CRM_ApiLog_DAO_ApiLogConfig',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'title' => [
          'name' => 'title',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Title'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_api_log_config.title',
          'table_name' => 'civicrm_api_log_config',
          'entity' => 'ApiLogConfig',
          'bao' => 'CRM_ApiLog_DAO_ApiLogConfig',
          'localizable' => 0,
          'add' => NULL,
        ],
        'entity_filter' => [
          'name' => 'entity_filter',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Entity Filter'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_api_log_config.entity_filter',
          'table_name' => 'civicrm_api_log_config',
          'entity' => 'ApiLogConfig',
          'bao' => 'CRM_ApiLog_DAO_ApiLogConfig',
          'localizable' => 0,
          'add' => NULL,
        ],
        'action_filter' => [
          'name' => 'action_filter',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Action Filter'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_api_log_config.action_filter',
          'table_name' => 'civicrm_api_log_config',
          'entity' => 'ApiLogConfig',
          'bao' => 'CRM_ApiLog_DAO_ApiLogConfig',
          'localizable' => 0,
          'add' => NULL,
        ],
        'request_filter' => [
          'name' => 'request_filter',
          'type' => CRM_Utils_Type::T_LONGTEXT,
          'title' => E::ts('Request Filter'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_api_log_config.request_filter',
          'table_name' => 'civicrm_api_log_config',
          'entity' => 'ApiLogConfig',
          'bao' => 'CRM_ApiLog_DAO_ApiLogConfig',
          'localizable' => 0,
          'add' => NULL,
        ],
        'response_filter' => [
          'name' => 'response_filter',
          'type' => CRM_Utils_Type::T_LONGTEXT,
          'title' => E::ts('Response Filter'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_api_log_config.response_filter',
          'table_name' => 'civicrm_api_log_config',
          'entity' => 'ApiLogConfig',
          'bao' => 'CRM_ApiLog_DAO_ApiLogConfig',
          'localizable' => 0,
          'add' => NULL,
        ],
        'success_filter' => [
          'name' => 'success_filter',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Success Filter'),
          'description' => E::ts('Success filter based on option group'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_api_log_config.success_filter',
          'default' => '1',
          'table_name' => 'civicrm_api_log_config',
          'entity' => 'ApiLogConfig',
          'bao' => 'CRM_ApiLog_DAO_ApiLogConfig',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'api_request_status',
            'optionEditPath' => 'civicrm/admin/options/api_request_status',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'api_log_config', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'api_log_config', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
